// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/terminal/BloombergDark.tsx": () => import("../components/mockups/terminal/BloombergDark.tsx"),
  "./components/mockups/terminal/ExcelPro.tsx": () => import("../components/mockups/terminal/ExcelPro.tsx"),
  "./components/mockups/terminal/InstitutionalSlate.tsx": () => import("../components/mockups/terminal/InstitutionalSlate.tsx")
};
