// Recovery for a failed dynamic import.
//
// Every route in App.tsx and PhoneShell.tsx is lazy(), so the app fetches
// a chunk on nearly every navigation. When that fetch fails the promise
// rejects, React propagates it to the nearest error boundary, and before
// this module existed the only boundary was RootErrorBoundary in
// main.tsx — which renders the raw TypeError and its stack. The user is
// then stuck on a broken page until they think to reload.
//
// ── Why a reload actually fixes the common case ────────────────────────
//
// Measured from the built service worker (artifacts/finance-tracker/
// public/sw.js, generated by vite-plugin-pwa with registerType
// "autoUpdate"): it contains skipWaiting, clientsClaim AND
// cleanupOutdatedCaches. So when a deploy lands while a tab is open, the
// new worker activates immediately, claims the running page, and deletes
// the previous precache — while that page's JavaScript is still running
// and still holds the OLD chunk hashes in its module graph. The next
// navigation to a not-yet-loaded route asks for a chunk that no longer
// exists in any cache. Whether it resolves then depends entirely on the
// host still serving the previous deployment's asset.
//
// A reload is the fix rather than a workaround: the new worker is
// already in control, so the reload is served the NEW index.html, whose
// chunk hashes exist. Recovery is not "try the same thing again" — the
// page genuinely comes back different.
//
// ── Why it reloads at most once ────────────────────────────────────────
//
// A chunk that is genuinely gone would reload forever, which is worse
// than the error it replaces. The attempt is recorded in sessionStorage
// (per-tab, cleared when the tab closes) and a second failure inside the
// window renders an honest surface instead.
//
// The window matters: without it, one unlucky reload would disable
// recovery for the rest of that tab's life, so a deploy an hour later
// would show the error page rather than healing. With it, the flag only
// suppresses a *tight* loop, which is the only thing it needs to do.

const ATTEMPT_KEY = "nr-chunk-reload-attempt";

// Long enough to cover a reload plus the app booting and the user
// reaching another lazy route; short enough that an unrelated failure
// later in the same tab still gets its own recovery.
export const RELOAD_WINDOW_MS = 30_000;

// Browsers word this differently and none of them give it a code:
//   Chrome/Edge  "Failed to fetch dynamically imported module: <url>"
//   Firefox      "error loading dynamically imported module"
//   Safari       "Importing a module script failed."
// The webpack-era forms are matched too — the app has not always been on
// Vite, and a stale bundle can still surface them.
const CHUNK_ERROR_PATTERNS = [
  /failed to fetch dynamically imported module/i,
  /error loading dynamically imported module/i,
  /importing a module script failed/i,
  /failed to load module script/i,
  /loading chunk \S+ failed/i,
  /chunkloaderror/i,
];

export function isChunkLoadError(error: unknown): boolean {
  if (!error) return false;
  const name = (error as { name?: unknown }).name;
  if (typeof name === "string" && /^chunkloaderror$/i.test(name)) return true;
  const message = (error as { message?: unknown }).message;
  const text = typeof message === "string" ? message : String(error);
  return CHUNK_ERROR_PATTERNS.some((p) => p.test(text));
}

// Storage is wrapped because sessionStorage throws outright in some
// privacy modes. A recovery path that can itself throw is not one.
function readAttempt(): number | null {
  try {
    const raw = sessionStorage.getItem(ATTEMPT_KEY);
    if (!raw) return null;
    const at = Number(raw);
    return Number.isFinite(at) ? at : null;
  } catch {
    return null;
  }
}

function writeAttempt(at: number): void {
  try {
    sessionStorage.setItem(ATTEMPT_KEY, String(at));
  } catch {
    /* storage unavailable — see shouldAttemptReload */
  }
}

export function clearChunkReloadAttempt(): void {
  try {
    sessionStorage.removeItem(ATTEMPT_KEY);
  } catch {
    /* nothing to clear if we could never write */
  }
}

// True when a reload has not already been tried for this incident.
//
// Records the attempt as a side effect, so two boundaries failing in the
// same tick cannot both decide to reload. If sessionStorage is
// unavailable the write is a no-op and the read returns null, so this
// keeps returning true — deliberately: in a private window with no
// storage, one reload per failure is still better than a raw TypeError,
// and the browser's own reload-loop protection is the backstop.
export function shouldAttemptReload(now: number = Date.now()): boolean {
  const last = readAttempt();
  if (last !== null && now - last < RELOAD_WINDOW_MS) return false;
  writeAttempt(now);
  return true;
}
