// Canonical list of all navigable hrefs — kept in sync with layout.tsx NAV_SECTIONS.
// Extracted here so persona.ts can reference it without importing the entire layout.
export const ALL_NAV_HREFS: string[] = [
  "/",
  "/accounts",
  "/transactions",
  "/upcoming",
  "/portfolio",
  "/investments",
  "/net-worth",
  "/tax",
  "/budget",
  "/goals",
  "/owing",
  "/split",
  "/subscriptions",
  "/calendar",
  "/decisions",
  "/analytics",
  "/ai-coach",
  "/health-score",
  "/cashflow",
  "/reports",
  "/projection",
  "/recurring",
  "/calculators",
  "/import",
  "/fire",
  "/pension",
  "/whatif",
  "/mortgage",
  "/year-review",
  "/settings",
];
