// Make a new deployment reach a tab that is already open.
//
// ── The failure this exists to stop ──────────────────────────────────────
//
// Five separate times, finished and correct work looked like nothing had
// happened, because the tab being looked at was running an old build. Each
// time a design that was already right was debugged instead.
//
// The cause is not the service worker's caching strategy. It is that the tab
// never asks. `registerSW.js`, generated by vite-plugin-pwa, is a single
// `navigator.serviceWorker.register('/sw.js')` on `load` and nothing else —
// measured in artifacts/finance-tracker/public/registerSW.js. After that one
// call the page holds its worker, its precache and its chunk hashes for as
// long as the tab lives. A browser re-checks a worker script on navigation
// and roughly once a day; a single-page app that never navigates does
// neither. So a tab left open across a deploy keeps serving the previous
// build indefinitely, and it does so silently and convincingly.
//
// lib/chunk-recovery.ts handles the other half — the tab that has taken the
// NEW worker and then asks for a chunk the old graph still points at. That
// one is reactive by nature: it can only fire once an import has already
// failed. This module is the proactive half, and between them the two cover
// both directions of the same deploy race.
//
// ── Why a reload is the right response ───────────────────────────────────
//
// The generated worker carries skipWaiting AND clientsClaim, so the moment
// an update is found the new worker activates and takes over the running
// page. At that instant the page's JavaScript is the old build and its
// controller is the new one, which is precisely the state that produces
// "Failed to fetch dynamically imported module". Reloading is not a
// workaround for that state, it is the exit from it: the new worker is
// already in control, so the reload is served the new index.html and the
// chunk hashes it names exist.

/** How often an open tab asks whether there is a newer build. */
export const UPDATE_POLL_MS = 60_000;

type Verdict = "reload" | "wait" | "ignore";

const NON_TEXT_INPUT = ["button", "submit", "reset", "checkbox", "radio", "file", "range", "image"];

/**
 * Whether the focused element holds text the user has actually written.
 *
 * A forced reload that throws away half a typed transaction would be a worse
 * bug than the one this module fixes, so the reload waits for the field to be
 * left rather than firing into it.
 *
 * "Holds text" and not "has focus". The first version of this tested focus
 * alone, and the end-to-end check found that the sign-in screen autofocuses
 * an EMPTY email field — so the guard was permanently on, and the whole
 * module was a no-op on the single page a forgotten tab is most likely to be
 * sitting on. An empty field has nothing to lose.
 */
export function isTyping(active: Element | null | undefined): boolean {
  if (active == null) return false;
  const el = active as HTMLElement;
  if (el.isContentEditable === true) return (el.textContent ?? "").trim().length > 0;
  const tag = (el.tagName ?? "").toUpperCase();
  if (tag !== "INPUT" && tag !== "TEXTAREA") return false;
  // A checkbox or a button holding focus is not composition. Only the
  // text-bearing input types carry something a reload would destroy.
  const type = ((el as HTMLInputElement).type ?? "text").toLowerCase();
  if (tag === "INPUT" && NON_TEXT_INPUT.includes(type)) return false;
  return ((el as HTMLInputElement).value ?? "").trim().length > 0;
}

/**
 * The whole decision, as a pure function, so it can be tested without a
 * service worker.
 *
 * `wasControlled` is the guard that matters, and it is deliberately the
 * state immediately BEFORE the change being judged, not the state at boot.
 * On a first-ever visit there is no worker; the one that installs claims the
 * page and fires the same `controllerchange` a real update fires, so that
 * one must be ignored — but only that one. Reading it once at boot instead
 * latches the whole tab: a browser profile's first-ever visit to the app
 * would then never pick up a deploy for as long as that tab stayed open,
 * which is the exact failure this module exists to remove. That is not a
 * theory; it is what the end-to-end check caught on the first run.
 */
export function decideReload(o: {
  wasControlled: boolean;
  alreadyReloading: boolean;
  typing: boolean;
}): Verdict {
  if (o.alreadyReloading) return "ignore";
  if (!o.wasControlled) return "ignore";
  if (o.typing) return "wait";
  return "reload";
}

let reloading = false;

/**
 * Start asking. No-op where there is no service worker at all — the dev
 * server (devOptions.enabled is false), the Capacitor WebView, a private
 * window that has them switched off.
 */
export function watchForNewBuild(): void {
  if (typeof navigator === "undefined" || !("serviceWorker" in navigator)) return;
  const sw = navigator.serviceWorker;
  // Tracked live, not captured at boot. See decideReload.
  let controlled = sw.controller != null;
  let pending = false;

  const attempt = (wasControlled: boolean): void => {
    const verdict = decideReload({
      wasControlled,
      alreadyReloading: reloading,
      typing: isTyping(document.activeElement),
    });
    if (verdict === "ignore") { pending = false; return; }
    if (verdict === "wait") { pending = true; return; }
    reloading = true;
    window.location.reload();
  };

  // The new worker has taken over this page. From here the running bundle
  // and its controller disagree about which build this is.
  sw.addEventListener("controllerchange", () => {
    const wasControlled = controlled;
    controlled = sw.controller != null;
    pending = true;
    attempt(wasControlled);
  });

  sw.ready
    .then((registration) => {
      const check = (): void => {
        // By the time the first poll runs the page is controlled, whether or
        // not it was when this module loaded. Recording that here is what
        // makes the NEXT controllerchange count as a real deploy.
        if (sw.controller != null) controlled = true;
        // A reload held back because the user was mid-sentence gets another
        // chance every time round, rather than being dropped.
        if (pending) { attempt(controlled); return; }
        if (document.visibilityState === "hidden") return;
        void registration.update().catch(() => { /* offline, or no worker yet */ });
      };
      window.setInterval(check, UPDATE_POLL_MS);
      // Coming back to the tab is the moment a stale build is most likely
      // and the moment the user is most likely to be looking at it.
      document.addEventListener("visibilitychange", () => {
        if (document.visibilityState === "visible") check();
      });
      window.addEventListener("online", check);
    })
    .catch(() => { /* no worker ever became ready */ });
}
