// Wise adapter. The one working per-user provider so far.
//
// The credential is a Wise personal API token, generated by the user at
// wise.com → Settings → API tokens. We never store it in plaintext; the
// caller decrypts on the way in and this adapter forgets it on the way
// out. Log lines redact the Authorization header (see logger.ts redact
// paths); errors surface Wise's own message but never the token.

import { logger } from "../lib/logger";
import type {
  ProviderAdapter,
  AdapterAccount,
  AdapterTransaction,
  ValidationResult,
} from "./types";
import { AdapterError } from "./types";

const WISE_ENV = process.env.WISE_ENV ?? "live";
const WISE_BASE_URL =
  WISE_ENV === "sandbox"
    ? "https://api.sandbox.transferwise.tech"
    : "https://api.transferwise.com";

interface WiseProfile {
  id: number;
  type: "personal" | "business";
  fullName?: string;
}

interface WiseBalance {
  id: number;
  currency: string;
  amount: { value: number; currency: string };
}

interface WiseTransaction {
  type: string;
  date: string;
  amount: { value: number; currency: string };
  totalFees: { value: number; currency: string };
  details: {
    type: string;
    description: string;
    merchant?: { name?: string };
  };
  referenceNumber: string;
}

async function wiseFetch<T>(credential: string, path: string): Promise<T> {
  let res: Response;
  try {
    res = await fetch(`${WISE_BASE_URL}${path}`, {
      headers: {
        Authorization: `Bearer ${credential}`,
        Accept: "application/json",
      },
    });
  } catch (err) {
    throw new AdapterError(
      "network",
      err instanceof Error ? err.message : "network failure calling Wise",
    );
  }
  if (res.status === 401 || res.status === 403) {
    // Do NOT log the Wise response body here — Wise usually echoes the
    // request auth header back in the WWW-Authenticate response header,
    // and even the JSON body can contain identifying context we would
    // rather keep out of the log stream.
    throw new AdapterError("auth", "Wise rejected the token");
  }
  if (res.status === 429) {
    throw new AdapterError("rate_limit", "Wise rate limit hit");
  }
  if (!res.ok) {
    // Non-auth errors: capture the body for the log so we can debug, but
    // still don't include the credential. The body is safe to log
    // because it's a Wise error message, not our request.
    const body = await res.text().catch(() => "");
    logger.error({ path, status: res.status, body }, "Wise API request failed");
    throw new AdapterError(
      res.status >= 500 ? "provider" : "invalid_response",
      `Wise API error ${res.status} on ${path}`,
    );
  }
  return res.json() as Promise<T>;
}

async function listProfiles(credential: string): Promise<WiseProfile[]> {
  return wiseFetch<WiseProfile[]>(credential, "/v2/profiles");
}

async function listBalances(credential: string, profileId: number): Promise<WiseBalance[]> {
  return wiseFetch<WiseBalance[]>(
    credential,
    `/v4/profiles/${profileId}/balances?types=STANDARD`,
  );
}

async function getStatement(
  credential: string,
  profileId: number,
  balanceId: number,
  currency: string,
  intervalStart: Date,
  intervalEnd: Date,
): Promise<WiseTransaction[]> {
  const params = new URLSearchParams({
    currency,
    intervalStart: intervalStart.toISOString(),
    intervalEnd: intervalEnd.toISOString(),
    type: "COMPACT",
  });
  const resp = await wiseFetch<{ transactions: WiseTransaction[] }>(
    credential,
    `/v3/profiles/${profileId}/balance-statements/${balanceId}/statement.json?${params}`,
  );
  return resp.transactions;
}

export const wiseAdapter: ProviderAdapter = {
  provider: "wise",

  async validateCredential(credential: string): Promise<ValidationResult> {
    try {
      const profiles = await listProfiles(credential);
      if (profiles.length === 0) {
        return { ok: false, error: "Wise token has no accessible profile" };
      }
      const personal = profiles.find((p) => p.type === "personal") ?? profiles[0];
      return { ok: true, label: personal.fullName ?? `Wise (${personal.type})` };
    } catch (err) {
      if (err instanceof AdapterError) {
        return { ok: false, error: err.message };
      }
      return { ok: false, error: err instanceof Error ? err.message : "Unknown error" };
    }
  },

  async listAccounts(credential: string): Promise<AdapterAccount[]> {
    const profiles = await listProfiles(credential);
    const personal = profiles.find((p) => p.type === "personal") ?? profiles[0];
    if (!personal) {
      throw new AdapterError("provider", "No Wise profile found for this token");
    }
    const balances = await listBalances(credential, personal.id);
    return balances.map((b) => ({
      externalId: String(b.id),
      label: `Wise (${b.currency})`,
      currency: b.amount.currency,
      balance: String(b.amount.value),
      providerMeta: { profileId: String(personal.id) },
    }));
  },

  async fetchTransactionsSince(
    credential: string,
    account: AdapterAccount,
    since: Date,
  ): Promise<AdapterTransaction[]> {
    const profileId = Number(account.providerMeta.profileId);
    if (!Number.isFinite(profileId)) {
      throw new AdapterError(
        "invalid_response",
        "account.providerMeta.profileId is missing or non-numeric",
      );
    }
    const balanceId = Number(account.externalId);
    if (!Number.isFinite(balanceId)) {
      throw new AdapterError(
        "invalid_response",
        "account.externalId is not a Wise balance id",
      );
    }
    const transactions = await getStatement(
      credential,
      profileId,
      balanceId,
      account.currency,
      since,
      new Date(),
    );
    return transactions.map((tx) => ({
      externalId: tx.referenceNumber,
      date: tx.date,
      description: tx.details.merchant?.name ?? tx.details.description ?? tx.details.type,
      // Wise sends signed amounts (negative = outflow) — keep the sign.
      nativeAmount: String(tx.amount.value),
      currency: tx.amount.currency,
    }));
  },
};
